// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/authz/": {
            "get": {
                "summary": "get configured authz",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "put": {
                "summary": "Create or update authz",
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/authzs3/": {
            "get": {
                "summary": "get configured authzs3",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "put": {
                "summary": "Create or update authz",
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/config/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get configured nodes",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/config/{node}": {
            "put": {
                "summary": "Create or update node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "summary": "Delete configured node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/config/{node}/clusters": {
            "put": {
                "summary": "Create or update cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/config/{node}/clusters/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves clisters configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "cluster id",
                        "name": "name",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "summary": "Delete configured cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "cluster id",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/config/{node}/configstatus": {
            "get": {
                "summary": "get node config status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/config/{node}/endpoints": {
            "put": {
                "summary": "Create or update endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/config/{node}/endpoints/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves endpoints configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "cluster id",
                        "name": "name",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "put": {
                "summary": "Update endpoint cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "summary": "Delete configured endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "cluster id",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "priority",
                        "name": "priority",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "endpoint address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/config/{node}/interfaces": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get configured node interfaces",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "put": {
                "summary": "Create or update node interface address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "summary": "Delete node interface address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/config/{node}/listeners": {
            "put": {
                "summary": "Create or update listener",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/config/{node}/listeners/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves listeners configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "listener id",
                        "name": "name",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "summary": "Delete configured listener",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "listener id",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/config/{node}/routes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get configured node routes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "put": {
                "summary": "Create or update node route",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "summary": "Delete configured routes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/config/{node}/secrets": {
            "put": {
                "summary": "Create or update cluster",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/config/{node}/secrets/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves listeners configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "secret id",
                        "name": "name",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "summary": "Delete configured listener",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "secret id",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/live/nodes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves list of worker nodes",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/live/nodes/{node}/clusters": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves list of clusters on node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/live/nodes/{node}/config_dump": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves node config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/live/nodes/{node}/listeners": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves list of listeners on node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/live/nodes/{node}/logging": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves logging level",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "summary": "Change loglevel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "node",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/live/nodes/{node}/sync": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves worker sync status",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/ratelimit/{domain}": {
            "get": {
                "summary": "get configured ratelimits",
                "parameters": [
                    {
                        "type": "string",
                        "description": "domain",
                        "name": "domain",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "put": {
                "summary": "Delete rate limit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "node id",
                        "name": "domain",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "envoy manager REST API",
	Description: "envoy manager server",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
